[package]
name = "pc_mqtt_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttc = "0.23.0"
serde_json = "1.0"
ctrlc = "3.4.1"
